# Info about vm.
os: linux
dist: xenial
language: scala
jdk:
  - openjdk11 # Java version. Add other Java versions under this.
scala:
  - 2.12.10 # Scala version. Add other Scala versions under this.

branches:
  only:
    - master # build master branch only.

# We've enabled by default coverage functionality.
script:
  - sbt compile
  - sbt test
  - sbt coverageReport
  - bash deploy.sh # generate static files.

# Deploy to GitHub some infos.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
