# Info about vm and jvm.
language: scala

dist: xenial

jdk:
  - openjdk11 # Java version. Add other Java versions under this.

scala:
  - 2.12.11 # Scala version. Add other Scala versions under this.
  # - 2.13.3 Last stable version

git:
  autocrlf: input

# Trigger build only on master branch.
branches:
  only:
    - master # build master branch only.
    - dev

# We've enabled by default coverage functionality.
# script:
#   - bash deploy.sh # generate static files.

# Send notifications to those address.
# notifications:
#   email:
#     recipients:
#       - d.tentoni@wedoit.io
#       - daniele.tentoni2@studio.unibo.it
#       - l.giorgetti@wedoit.io
#       - luca.giorgetti@studio.unibo.it
#       - lorenzo.pagnini@studio.unibo.it
#       - daniele.tentoni.1996@gmail.com
#     on_success: change
#     on_failure: always

jobs:
  exclude:
    - os: windows # Windows dose not compile in scala.
      language: scala
  include:
    - stage: Run sbt on Linux openjdk11
      os: linux
      script: sbt clean compile test
    - stage: Run sbt on Macos openjdk11
      os: osx
      script: sbt clean compile test
    - stage: Deploy to Github Pages
      script: bash deploy.sh
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        keep_history: true
        on:
          branches:
            - master
            - dev
        local_dir: public
    - stage: Deploy to Github Releases
      script: bash deploy.sh
      deploy:
        provider: releases
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        file_glob: true
        file: client/target/scala-*/*SNAPSHOT.jar
        on:
          branch: master
          # tags: true