# Info about vm and jvm.
language: scala

os:
  - linux
  - osx
  - windows

dist: xenial

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk11 # Java version. Add other Java versions under this.

scala:
  - 2.12.11 # Scala version. Add other Scala versions under this.
  - 2.13.3

# Trigger build only on master branch.
branches:
  only:
    - master # build master branch only.

jobs:
  exclude:
    - dist: xenial
      jdk:
        - oraclejdk8
   # - jdk:
   #     - oraclejdk8
   #   os: osx



# We've enabled by default coverage functionality.
script:
  - bash deploy.sh # generate static files.

# Send notifications to those address.
# notifications:
#   email:
#     recipients:
#       - d.tentoni@wedoit.io
#       - daniele.tentoni2@studio.unibo.it
#       - l.giorgetti@wedoit.io
#       - luca.giorgetti@studio.unibo.it
#       - lorenzo.pagnini@studio.unibo.it
#       - daniele.tentoni.1996@gmail.com
#     on_success: change
#     on_failure: always

# Deploy to GitHub some infos.
deploy:
  - provider: pages
    cleanup: false
    token: $GH_TOKEN
    keep_history: true
    on:
      branch: master
    local_dir: public
  - provider: releases
    cleanup: false
    token: $GH_TOKEN
    on:
      branch: master
      tags: true
