# Info about vm and jvm.
language: scala # The project language.

dist: xenial # Default distro for linux vm.

jdk:
  - openjdk11 # Java version. Add other Java versions under this.

install: true

scala:
  - 2.12.11 # Scala version. Add other Scala versions under this.
  # - 2.13.3 Last stable version

git:
  autocrlf: input

# Trigger build only on master branch.
branches:
  only:
    - master # build master branch only.
    - dev

# These directories are cached to S3 at the end of the build.
cache:
  directories:
    - $HOME/.ivy2/cache
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.cache/coursier
    - $HOME/.sbt

script:
  - bash travis_scripts/compile_for_release.sh
  # Set up git user name and tag this commit.
  - git config --local user.name "Daniele Tentoni"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  token: $GH_TOKEN
  file_glob: true
  file:
    - client/target/scala-*/*SNAPSHOT.jar
    - server/target/scala-*/*SNAPSHOT.jar
  on:
    branch: master
    tags: true