# Info about vm and jvm.
language: scala

dist: xenial

jdk:
  - openjdk11 # Java version. Add other Java versions under this.

scala:
  - 2.12.11 # Scala version. Add other Scala versions under this.
  # - 2.13.3 Last stable version

git:
  autocrlf: input

# Trigger build only on master branch.
branches:
  only:
    - master # build master branch only.
    - dev

# We've enabled by default coverage functionality.
# script:
#   - bash deploy_to_pages.sh # generate static files.

# Send notifications to those address.
# notifications:
#   email:
#     recipients:
#       - d.tentoni@wedoit.io
#       - daniele.tentoni2@studio.unibo.it
#       - l.giorgetti@wedoit.io
#       - luca.giorgetti@studio.unibo.it
#       - lorenzo.pagnini@studio.unibo.it
#       - daniele.tentoni.1996@gmail.com
#     on_success: change
#     on_failure: always

jobs:
  include:
    - stage: Run sbt with openjdk11
      os: linux
      script: sbt compile coverage test
    - stage: Run sbt with openjdk11
      os: osx
      script: sbt compile coverage test
    - stage: Deploy to Github Pages
      script: bash travis_scripts/deploy_to_pages.sh
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        keep_history: true
        on:
          branch: dev
        local_dir: public
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: Deploy to Github Releases
      script: bash travis_scripts/compile_for_release.sh # Deploying artifacts need only compile.
      deploy:
        provider: releases
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        file_glob: true
        file:
          - client/target/scala-*/*SNAPSHOT.jar
          - server/target/scala-*/*SNAPSHOT.jar
        on:
          branch: master
          tags: true

stages:
  - name: Run sbt with openjdk11
    if: (type = pull_request OR type = push) AND (branch = master OR branch = dev)
  - name: Deploy to Github Pages
    if: type = push AND (branch = master OR branch = dev)
  - name: Deploy to Github Releases
    if: type = push AND branch = master