# Info about vm.
os: linux
dist: xenial
language: scala
jdk:
  - openjdk11 # Java version. Add other Java versions under this.
scala:
  - 2.12.10 # Scala version. Add other Scala versions under this.

branches:
  only:
    - master # build master branch only.

# We've enabled by default coverage functionality.
script:
  - bash deploy.sh # generate static files.

notifications:
  email:
    - recipients:
      - d.tentoni@wedoit.io
      - daniele.tentoni2@studio.unibo.it
      - l.giorgetti@wedoit.io
      - luca.giorgetti@studio.unibo.it
      - lorenzo.pagnini@studio.unibo.it
      - daniele.tentoni.1996@gmail.com
    on_success: change
    on_failure: always

# Deploy to GitHub some infos.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
