# Info about vm and jvm.
language: scala

os: 
  - linux
  - osx
  
dist: 
  - xenial
  - trusty
  
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11 # Java version. Add other Java versions under this.
  
scala:
  - 2.12.11 # Scala version. Add other Scala versions under this.
  - 2.13.3

# Trigger build only on master branch.
branches:
  only:
    - master # build master branch only.

# We've enabled by default coverage functionality.
script:
  - bash deploy.sh # generate static files.

# Send notifications to those address.
# notifications:
#   email:
#     recipients:
#       - d.tentoni@wedoit.io
#       - daniele.tentoni2@studio.unibo.it
#       - l.giorgetti@wedoit.io
#       - luca.giorgetti@studio.unibo.it
#       - lorenzo.pagnini@studio.unibo.it
#       - daniele.tentoni.1996@gmail.com
#     on_success: change
#     on_failure: always

# Deploy to GitHub some infos.
deploy:
  provider: pages
  cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  cleanup: true
  on:
    branch: master
    tags: true
